<a href="https://colab.research.google.com/github/kwon0136/Python/blob/master/190222/solution_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:



'''
url = 'https://movie.naver.com/movie/sdb/rank/rmovie.nhn?sel=cur&date=20190221'
with urllib.request.urlopen(url) as response:
    html = response.read()
    soup = BeautifulSoup(html, 'html.parser')

titles = soup.find_all("div",{"class": "tit5"})
ratings = soup.find_all("td",{"class": "point"})
#print(titles[0].a.string, ratings[0].string)
#len(titles)
data = []
for i in range(len(titles)):
    #print(titles[i].a.string, ratings[i].string)
    data.append([titles[i].a.string, ratings[i].string])

df = pd.DataFrame(data, columns=['title', 'rating'])
#df.shape
#df.head()
from matplotlib import font_manager, rc
font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
rc('font', family=font_name)
import matplotlib.pyplot as plt
x = list(df['title'].head())
y = list(df['rating'].head().astype(float))
plt.plot(x,y)
plt.show()

# 20190122 ~ 20190221 네이버 영화 제목에 대한 평점에 대한 평균구하고 
# 그래프로 출력하시오. 
'''

'\nurl = \'https://movie.naver.com/movie/sdb/rank/rmovie.nhn?sel=cur&date=20190221\'\nwith urllib.request.urlopen(url) as response:\n    html = response.read()\n    soup = BeautifulSoup(html, \'html.parser\')\n\ntitles = soup.find_all("div",{"class": "tit5"})\nratings = soup.find_all("td",{"class": "point"})\n#print(titles[0].a.string, ratings[0].string)\n#len(titles)\ndata = []\nfor i in range(len(titles)):\n    #print(titles[i].a.string, ratings[i].string)\n    data.append([titles[i].a.string, ratings[i].string])\n\ndf = pd.DataFrame(data, columns=[\'title\', \'rating\'])\n#df.shape\n#df.head()\nfrom matplotlib import font_manager, rc\nfont_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()\nrc(\'font\', family=font_name)\nimport matplotlib.pyplot as plt\nx = list(df[\'title\'].head())\ny = list(df[\'rating\'].head().astype(float))\nplt.plot(x,y)\nplt.show()\n\n# 20190122 ~ 20190221 네이버 영화 제목에 대한 평점에 대한 평균구하고 \n# 그래프로 출력하시오. \n'

In [0]:
from bs4 import BeautifulSoup
import pandas as pd

import urllib.request
import urllib.parse

#sel_dates = ['20190118', '20190119', '20190220', '20190221']
#for d in range(len(sel_dates)):
#   print(sel_dates[i])
data = []
for d in pd.date_range('2019-01-18', periods=35):
    #print(d.strftime('%Y%m%d')) # strftime 
    # %Y 2019, %m 01, %d 18
    sel_date = d.strftime('%Y%m%d')
    url = 'https://movie.naver.com/movie/sdb/rank/rmovie.nhn?sel=cur&date=' + sel_date
    
    with urllib.request.urlopen(url) as response:
        html = response.read()
        soup = BeautifulSoup(html, 'html.parser')

    titles = soup.find_all("div",{"class": "tit5"})
    ratings = soup.find_all("td",{"class": "point"})
    #print(titles[0].a.string, ratings[0].string)
    #len(titles)
    for i in range(len(titles)):
        #print(titles[i].a.string, ratings[i].string)
        data.append([titles[i].a.string, ratings[i].string])

data

                                title rating
0                                그린 북   9.67
1                                 언더독   9.53
2                            보헤미안 랩소디   9.47
3                          폴란드로 간 아이들   9.43
4                               헌터 킬러   9.40
5                       스파이더맨: 뉴 유니버스   9.26
6                              러빙 빈센트   9.21
7                 극장판 공룡메카드: 타이니소어의 섬   9.19
8               점박이 한반도의 공룡2 : 새로운 낙원   9.18
9                                  바울   9.17
10                             인생 후르츠   9.15
11                            스타 이즈 본   9.15
12                              타샤 튜더   9.14
13                                 로마   9.10
14                  극장판 포켓몬스터 모두의 이야기   9.03
15                                말모이   9.02
16                            어거스트 러쉬   9.00
17                              디어 헌터   8.89
18                                소공녀   8.87
19                             내안의 그놈   8.79
20                  주먹왕 랄프 2: 인터넷 속으로   8.76
21                               라라랜드   8.59
22                               스윙키즈   8.48
23    극장판 짱구는 못말려: 아뵤! 쿵후 보이즈 ~라면 대란~   8.45
24                                 영주   8.44
25                          티파니에서 아침을   8.40
26                               아쿠아맨   8.38
27                       그랜드 부다페스트 호텔   8.38
28                                그린치   8.36
29                                범블비   8.18
...                               ...    ...
1438                           러빙 빈센트   9.21
1439                               바울   9.17
1440              극장판 공룡메카드: 타이니소어의 섬   9.16
1441                          스타 이즈 본   9.15
1442                           인생 후르츠   9.10
1443                               로마   9.09
1444                              말모이   9.06
1445                               증인   9.04
1446                            일일시호일   8.84
1447                           레고 무비2   8.83
1448              극장판 헬로카봇:옴파로스 섬의 비밀   8.79
1449                       알리타: 배틀 엔젤   8.77
1450                주먹왕 랄프 2: 인터넷 속으로   8.73
1451                             극한직업   8.69
1452                         어둠 속의 댄서   8.43
1453                               레토   8.41
1454                       메리 포핀스 리턴즈   8.34
1455                           내안의 그놈   8.31
1456                      해피 데스데이 2 유   7.88
1457                        님포매니악 볼륨2   7.79
1458                        님포매니악 볼륨1   7.61
1459                              사바하   7.56
1460                            블랙 팬서   7.50
1461                           콜드 체이싱   6.87
1462                          안티크라이스트   6.52
1463                               뺑반   6.50
1464                              타이탄   6.32
1465                          미래의 미라이   6.15
1466                           기묘한 가족   5.65
1467                        PMC: 더 벙커   5.24

[1468 rows x 2 columns]

In [0]:
df = pd.DataFrame(data, columns=['title', 'rating'])
#df.shape
#df.columns
df['rating'] = df['rating'].astype(float)
#df.info()
df2 =df.groupby('title')['rating'].mean()
df3 = df2.reset_index()
df4 = df3.sort_values('rating', ascending=False)
df5 = df4.head()
df5

         title    rating
7         그린 북  9.650286
2         가버나움  9.586800
67         언더독  9.453714
43    보헤미안 랩소디  9.448286
82  폴란드로 간 아이들  9.408571